version: '3'

services: 
  backend:
    build: ./backend
    ports:
      - "4000:4000"
    depends_on: 
      - mongo
    command: npm start
    networks: 
        - db-tier
        - backofficeNetwork
        - frontendNetwork

  backoffice:
    build: ./frontend
    ports:
      - "4200:80"
    depends_on: 
      - backend
    networks: 
      - backofficeNetwork

  frontend:
    build: ./unihub_app
    ports:
      - "8080:8080"
    depends_on: 
      - backend
    networks: 
      - frontendNetwork

  mongo:
        image: mongo
        restart: always
        volumes:
          - mongo-data:/data/db
        networks:
          - db-tier

networks:
  backofficeNetwork:
  frontendNetwork:

  db-tier:
    driver: bridge

volumes:
    mongo-data:
        driver: local